// Copyright (c) 2017-2022 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

#include "worker-source.h"

#include <workerd/rust/wasm-analysis/lib.rs.h>

#include <kj-rs/kj-rs.h>

namespace workerd {

using namespace kj_rs;
using namespace workerd::rust;

namespace {

kj::Maybe<WorkerLanguage> checkWasmLanguage(kj::ArrayPtr<const kj::byte> wasmData) {
  auto rustResult = wasm_analysis::check_wasm_language(wasmData.as<Rust>());

  switch (rustResult) {
    case wasm_analysis::WorkerLanguage::Rust:
      return WorkerLanguage::RUST;
    case wasm_analysis::WorkerLanguage::CommunityGo:
      return WorkerLanguage::COMMUNITY_GO;
    case wasm_analysis::WorkerLanguage::Unknown:
      return kj::none;
  }

  return kj::none;
}

}  // namespace

/**
 * Since Wasm can be imported in many contexts, we have to formally define what it means for
 * a bundle to be "written in a language". We use the following simple detection process here:
 *
 * 1. The first Wasm file has a convention or metadata that it is of a known language toolchain.
 * 2. The first Wasm file also exports a known fetch implementation function.
 * 3. The entry point JS module imports the Wasm file.
 *
 * The goal in the above is to be sure beyond a reasonable doubt that we can correctly classify
 * most bundle variations generated by a supported language toolchain being tracked, assuming
 * non-malicious attempts at faking detection. Any variations of the toolchain over time in its
 * structure also therefore need to be taken into account, but by having a relatively general
 * detection above and explicitly manging a short list of tracked toolchains, this maintenance
 * should be minimal.
 *
 * We do not attempt to classify cases where users happen to be using another language Wasm
 * dependency as part of their JS Worker code. We only want to know the top-level language of
 * Worker authorship. All other cases must still be counted as JS. Even if having JS dependencies
 * used from another language is also still counted as the worker "being written in" the top-level
 * language. Language toolchains based on splitting up Wasm into multiple Wasm binaries are also
 * not currently supported.
 *
 * We aim to rather under-classify than over-classifying non-JS toolchains, so that
 * "WorkerLanguage::JS" really means JS not formally known to be created by a tracked language
 * toolchain. The important point is known non JS toolchains are only counted with clear certainty.
 * While custom build systems could in theory fake these detections, there is no known incentive to
 * do so (short of the author wanting to see more growth in language support!).
 *
 * Python remains an exception here in having its own compatibility flag and we only track this
 * official Python support.
 */
WorkerLanguage detectLanguage(const WorkerSource& source) {
  // Check if it's a Python worker
  if (source.variant.is<WorkerSource::ModulesSource>() &&
      source.variant.get<WorkerSource::ModulesSource>().isPython) {
    return WorkerLanguage::PYTHON;
  }

  // Script-based workers (Service Worker syntax) are always JS
  if (source.variant.is<WorkerSource::ScriptSource>()) {
    return WorkerLanguage::JS;
  }

  // For module-based workers, analyze the modules
  const auto& modulesSource = source.variant.get<WorkerSource::ModulesSource>();
  kj::StringPtr mainName = modulesSource.mainModule;

  kj::Maybe<kj::StringPtr> wasmName = kj::none;
  kj::Maybe<kj::ArrayPtr<const kj::byte>> wasmContent = kj::none;
  kj::Maybe<kj::StringPtr> mainContent = kj::none;

  for (const auto& module: modulesSource.modules) {
    kj::StringPtr name = module.name;
    const auto& content = module.content;

    if (content.is<WorkerSource::EsModule>()) {
      if (name == mainName) {
        mainContent = content.get<WorkerSource::EsModule>().body;
      }
    } else if (content.is<WorkerSource::WasmModule>()) {
      if (wasmContent == kj::none) {
        wasmName = name;
        wasmContent = content.get<WorkerSource::WasmModule>().body;
      } else {
        // More than one Wasm -> not a known language toolchain currently
        return WorkerLanguage::JS;
      }
    }
  }

  if (wasmContent == kj::none || mainContent == kj::none) return WorkerLanguage::JS;

  kj::StringPtr wasmFileName = KJ_ASSERT_NONNULL(wasmName);
  kj::ArrayPtr<const kj::byte> wasmData = KJ_ASSERT_NONNULL(wasmContent);
  kj::StringPtr mainData = KJ_ASSERT_NONNULL(mainContent);

  // Perform an analysis of the Wasm binary toolchain info.
  // Validates (1), (2) as stated above.
  KJ_IF_SOME(language, checkWasmLanguage(wasmData)) {
    // To verify (3), check for a valid Wasm import statement in JS main entry file
    if (wasm_analysis::check_has_import(
            mainData.as<Rust>(), mainName.as<Rust>(), wasmFileName.as<Rust>())) {
      return language;
    }
  }

  return WorkerLanguage::JS;
}

kj::StringPtr KJ_STRINGIFY(const WorkerLanguage& l) {
  switch (l) {
    case WorkerLanguage::RUST:
      return "rust"_kj;
    case WorkerLanguage::JS:
      return "js"_kj;
    case WorkerLanguage::COMMUNITY_GO:
      return "community-go"_kj;
    case WorkerLanguage::PYTHON:
      return "python"_kj;
  }
  KJ_UNREACHABLE;
}

}  // namespace workerd
