exports_files(
    [
        "rust-index.wasm",
        "rust-shim.mjs",
        "gomain.js",
        "go-app.wasm",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test-fixtures",
    srcs = [
        "go-app.wasm",
        "gomain.js",
        "rust-index.wasm",
        "rust-shim.mjs",
    ],
    visibility = ["//visibility:public"],
)
